"use client";

import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";

export default function Home() {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["health"],
    queryFn: api.health,
  });

  const ok = data?.status === "ok";
  const dot = isLoading
    ? "var(--text-muted)"
    : ok
      ? "var(--up)"
      : "var(--down)";
  const label = isLoading
    ? "connecting…"
    : ok
      ? "backend: ok"
      : "backend: unreachable";

  return (
    <main
      style={{
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        padding: "48px",
        maxWidth: 900,
        margin: "0 auto",
      }}
    >
      <header style={{ marginBottom: 32 }}>
        <h1
          style={{
            fontSize: 28,
            letterSpacing: "-0.02em",
            margin: 0,
          }}
        >
          Tearsheet
        </h1>
        <p style={{ color: "var(--text-muted)", marginTop: 4 }}>
          AI equity-research terminal · Phase 0 scaffold
        </p>
      </header>

      <section
        style={{
          background: "var(--panel)",
          border: "1px solid var(--border)",
          padding: "20px 24px",
          display: "flex",
          alignItems: "center",
          gap: 12,
        }}
      >
        <span
          aria-hidden
          style={{
            width: 9,
            height: 9,
            borderRadius: "50%",
            background: dot,
            boxShadow: `0 0 0 3px color-mix(in srgb, ${dot} 18%, transparent)`,
          }}
        />
        <span className="mono" style={{ fontSize: 14 }}>
          {label}
        </span>
        {ok && (
          <span
            className="mono"
            style={{ color: "var(--text-muted)", fontSize: 13 }}
          >
            {data?.app} v{data?.version} · data: {data?.data_source} · anthropic:{" "}
            {data?.integrations.anthropic ? "on" : "off"} · fred:{" "}
            {data?.integrations.fred ? "on" : "off"}
          </span>
        )}
        {isError && (
          <span
            className="mono"
            style={{ color: "var(--down)", fontSize: 13 }}
          >
            {(error as Error)?.message}
          </span>
        )}
      </section>

      <footer
        className="mono"
        style={{
          marginTop: "auto",
          paddingTop: 48,
          color: "var(--text-muted)",
          fontSize: 12,
        }}
      >
        Generated by AI from public sources · research tool, not financial advice
      </footer>
    </main>
  );
}
