"use client";

import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import {
  Overview, Financials, Valuation, Dcf, Analysis, Events, Interpretation, MoveExplain, News,
} from "@/components/panels";

const DEFAULT = "NVDA";

export default function Home() {
  const [ticker, setTicker] = useState(DEFAULT);
  const [input, setInput] = useState("");
  const [recent, setRecent] = useState<string[]>([DEFAULT]);
  const health = useQuery({ queryKey: ["health"], queryFn: api.health });

  useEffect(() => {
    setRecent((r) => [ticker, ...r.filter((x) => x !== ticker)].slice(0, 8));
  }, [ticker]);

  function submit(e: React.FormEvent) {
    e.preventDefault();
    const v = input.trim().toUpperCase();
    if (v) { setTicker(v); setInput(""); }
  }

  const ok = health.data?.status === "ok";
  const dot = health.isLoading ? "var(--text-muted)" : ok ? "var(--up)" : "var(--down)";

  return (
    <div className="app">
      <aside className="rail">
        <div className="brand">Tearsheet<span className="dot">.</span></div>
        <div className="subtle" style={{ fontSize: 12, marginTop: 2 }}>equity research terminal</div>

        <div className="rail-label">Lookup</div>
        <form onSubmit={submit}>
          <input
            className="search" placeholder="TICKER" value={input}
            onChange={(e) => setInput(e.target.value)} aria-label="ticker search" spellCheck={false}
          />
        </form>

        <div className="rail-label">Recent</div>
        <ul className="recent">
          {recent.map((r) => (
            <li key={r} className={r === ticker ? "active" : ""} onClick={() => setTicker(r)}>{r}</li>
          ))}
        </ul>

        <div className="rail-label">Sample tickers</div>
        <div className="subtle mono" style={{ fontSize: 12 }}>NVDA (offline sample)</div>

        <div className="status-line">
          <span className="dot-ind" style={{ background: dot }} />
          <span>{health.isLoading ? "connecting…" : ok ? "backend ok" : "backend down"}</span>
        </div>
        {ok && (
          <div className="subtle mono" style={{ fontSize: 11, marginTop: 6 }}>
            data: {health.data?.data_source} · anthropic: {health.data?.integrations.anthropic ? "on" : "off"} · fred: {health.data?.integrations.fred ? "on" : "off"}
          </div>
        )}
      </aside>

      <main className="main">
        <Overview ticker={ticker} index={0} />
        <Interpretation ticker={ticker} index={1} />
        <MoveExplain ticker={ticker} index={2} />
        <Analysis ticker={ticker} index={3} />
        <Dcf ticker={ticker} index={4} />
        <Valuation ticker={ticker} index={5} />
        <Events ticker={ticker} index={6} />
        <Financials ticker={ticker} index={7} />
        <News ticker={ticker} index={8} />

        <div className="footer">
          Generated by AI from public sources · research tool, not financial advice · no buy/sell/hold, no price target<br />
          Data: {health.data?.data_source ?? "—"} · provenance traced per figure · {new Date().getUTCFullYear()} · Tearsheet
        </div>
      </main>
    </div>
  );
}
